/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
    },
    extend: {
      screens: {
        "mobile" : "390px",
        "xxs" : "414px",
        'xxs470' : "470px",
        'xxs500' : "500px",
        "xs" : "540px",
        "xs590" : "590px",
        "xs615" : "615px",
        "sm660" : "660px",
        "sm705" : "705px",
        "sm725" : "725px",
        "md800" : "800px",
        "md835" : "835px",
        "md865" : "865px",
        "md895" : "895px",
        "md920" : "920px",
        "md955" : "955px",
        "md985" : "985px",
        "md1000" : "1000px",
        "lg1050" : "1050px",
        "lg1085" : "1085px",
        "lg1120" : "1120px",
        "6xl" : '1152px',
        "lg1180" : "1180px",
        "lg1220" : "1220px",
        "lg1250" : "1250px",
        "7xl" : '1280px',
        "xl1310" : "1310px",
        "xl1345" : "1345px",
        "xl1375" : "1375px",
        "xl1400" : "1400px",
        "xl1425" : "1425px",
        "xl1500" : "1500px",
        "xl1550" : "1550px",
        "xl1600" : "1600px",
        "xl1650" : "1650px",
        "xl1720" : "1720px",
        "xl1780" : "1780px",
        "xl1850" : "1850px",
        "xl1930" : "1930px",
        'ts1989' : "1989px",
        "xl2080" : "2080px",
        "xl2140" : "2140px",
        "xl2200" : "2200px",
      },
      flex: {
        full: "0 0 100%",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        zoomOut: {
          "0%": { transform: "scale(1.1)" },
          "100%": { transform: "scale(1)" },
        },
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        zoomOut : "zoomOut 1.5s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("tailwind-scrollbar-hide")],
};
